apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: misacademy/two-tier:v1
        env:
          - name: MYSQL_HOST
            value: "mysql-service.mysql-db.svc.cluster.local"
          - name: MYSQL_PASSWORD
            value: "admin"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_DB
            value: "mysql"
        ports:
          - containerPort: 5000  
